%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% PLOT A 3D ZERNIKE WAVEFRONT
% -------
%   Created By: Brianna J. Hobert
%   Date Created: 13 Aug. 2026
%   Beta tested: Jim Scire, Sean Peters, Jared Plotkin, Avinash Somwaru
%   Optical Diagnostics Lab at the New York Institute of Technology
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   This function generates a Zernike wavefront, where you can plot it
%   using the plotzern function. 
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% CITE THIS CODE AS
% -------
% [X] Hobert, Brianna (2026). Zernike Creator and Decomposer Toolbox
%     MATLAB Central File Exchange. Retrieved Month Day, Year. 
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

clc; clear all; close all; 

[zern,wf1,wf2,pupil]=quickZern(6,1,'gridsize',1024,'mode','burnside');
fig=plotzern(wf1,'pupil',pupil, ...
    'title','$Z_{6}^{-1}$', ...
    'xlabel','X Axis', ...
    'ylabel','Y Axis', ...
    'zlabel','Z Axis', ...
    'xlim','auto', ...
    'ylim','auto', ...
    'zlim',[-4,4], ...
    'fontsize',24, ...
    'cmap','jet', ...
    'cbar',1, ...
    'background','white', ...
    'axis','tight', ...
    'grid','on', ...
    'lighting','gouraud', ...
    'edgecolor','none', ...
    'view',[-40,50]);